[workspace]
resolver = "2"
members = [
    "packages/ui",
    {%- for member in workspace_members %}
    "{{- member -}}",
    {%- endfor %}
]

[workspace.dependencies]
dioxus = { {{ dioxus_dep_src }} }

# workspace
ui = { path = "packages/ui" }
{% if is_fullstack -%}
api = { path = "packages/api" }
{%- endif %}
